### ISSUE TITLE
istioctl panic doing kube-inject

### ISSUE THREAD

**Issue by esnible** [istio/manager#457]
I believe _istio/istio/tests/commonUtils.sh_:67 is doing `${ISTIOCLI} kube-inject -f ${before} -o ${after} --hub ${hub} --tag ${tag}` and failing with the following output and backtrace.

The backtrace is

```
#################################
Generating bookinfo yaml in /tmp/kubetest.dzknX/bookinfo
#################################

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1265736]

goroutine 1 [running]:
main.glob..func1(0x1d0fbc0, 0xc42005bb80, 0x0, 0xa, 0x0, 0x0)
	/home/jenkins/.cache/bazel/_bazel_jenkins/57429c5a8b62b4c619ad2679df08a6bd/bazel-sandbox/1cfe7b92-04f5-43ca-b151-df68d72ce26a-20/execroot/manager/bazel-out/local-fastbuild/bin/cmd/istioctl/istioctl.a.dir/istio.io/manager/cmd/istioctl/inject.go:88 +0xc6
github.com/spf13/cobra.(*Command).execute(0x1d0fbc0, 0xc42005ba40, 0xa, 0xa, 0x1d0fbc0, 0xc42005ba40)
	/home/jenkins/.cache/bazel/_bazel_jenkins/57429c5a8b62b4c619ad2679df08a6bd/bazel-sandbox/2e2a1796-1f3f-47c2-bbc9-8eb70dbe2b14-71/execroot/manager/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:599 +0x3e9
github.com/spf13/cobra.(*Command).ExecuteC(0x1d0fde0, 0x1, 0x0, 0x0)
	/home/jenkins/.cache/bazel/_bazel_jenkins/57429c5a8b62b4c619ad2679df08a6bd/bazel-sandbox/2e2a1796-1f3f-47c2-bbc9-8eb70dbe2b14-71/execroot/manager/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:689 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1d0fde0, 0xc4200001a0, 0xc4200001a0)
	/home/jenkins/.cache/bazel/_bazel_jenkins/57429c5a8b62b4c619ad2679df08a6bd/bazel-sandbox/2e2a1796-1f3f-47c2-bbc9-8eb70dbe2b14-71/execroot/manager/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:648 +0x2b
main.main()
	/home/jenkins/.cache/bazel/_bazel_jenkins/57429c5a8b62b4c619ad2679df08a6bd/bazel-sandbox/1cfe7b92-04f5-43ca-b151-df68d72ce26a-20/execroot/manager/bazel-out/local-fastbuild/bin/cmd/istioctl/istioctl.a.dir/istio.io/manager/cmd/istioctl/main.go:298 +0x2d
```

**Comment by esnible** [comment]
Fix is in the commit https://github.com/istio/manager/pull/446/commits/57c6c434549c74ff07449cee9b05f77f800e4550
